<?php


namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;

class IncidentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('email',EmailType::class,[
                'attr'=>['class'=>'form-control','placeholder'=>'Votre email']
            ])
            ->add('description',TextareaType::class,[
                'attr'=>['class'=>'form-control','placeholder'=>'Description de l\'incident','rows'=>8]
            ]);

    }
}