<?php
/**
 * Created by PhpStorm.
 * User: gauthierbosson
 * Date: 04/03/2019
 * Time: 11:40
 */

namespace App\Admin;


use App\Entity\Trashs;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class TrashAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $user = $this->getConfigurationPool()->getContainer()->get('security.token_storage')->getToken()->getUser();

        $inseeUrl = 'https://geo.api.gouv.fr/communes?nom=' . $user->getCity() . '&fields=departement';
        $file = file_get_contents($inseeUrl);
        $json = json_decode($file, true);
        $code = $json[0]['code'];


        $formMapper->add('city', HiddenType::class, [
            'label' => 'Ville',
            'data' => $user->getCity()
        ]);
        $formMapper->add('address', TextType::class, [
            'label' => 'Adresse'
        ]);
        $formMapper->add('inseeCode', HiddenType::class, [
            'label' => 'Code Insee',
            'data' => $code
        ]);
        $formMapper->add('reference', TextType::class, [
            'label' => 'Référence'
        ]);
        $formMapper->add('capacityMax', TextType::class, [
            'label' => 'Capacité maximum'
        ]);
        $formMapper->add('actualCapacity', TextType::class, [
            'label' => 'Capacité actuelle'
        ]);
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper->add('city');
        $datagridMapper->add('address');
        $datagridMapper->add('inseeCode');
        $datagridMapper->add('latitude');
        $datagridMapper->add('longitude');
        $datagridMapper->add('altitude');
        $datagridMapper->add('reference');
        $datagridMapper->add('capacityMax');
        $datagridMapper->add('actualCapacity');
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('reference', null, [
                'route' => [
                    'name' => 'show'
                ]
            ]);
        $listMapper->add('address');
        $listMapper->add('actualCapacity');
    }

    public function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->with('Benne ', [
                'class'       => 'col-md-12',
                'box_class'   => 'box box-solid box-primary',
                'description' => 'Votre benne',
            ])
            ->add('reference', null, ['label' => 'Référence'])
            ->add('address', null, ['label' => 'Adresse'])
            ->add('actualCapacity', null, ['label' => 'Capacité'])
            ->end()
            ->end()
        ;
    }

    public function toString($object)
    {
        return $object instanceof Trashs
            ? $object->getReference()
            : 'Trash';
    }

    public function createQuery($context = 'list')
    {
        $user = $this->getConfigurationPool()->getContainer()->get('security.token_storage')->getToken()->getUser();
        $query = parent::createQuery($context);
        $query->andWhere(
            $query->expr()->eq($query->getRootAliases()[0] . '.city', ':my_param')
        );
        $query->setParameter('my_param', $user->getCity());
        return $query;
    }

    public function prePersist($object)
    {
        parent::prePersist($object); // TODO: Change the autogenerated stub
        $city = $object->getCity();
        $address = $object->getAddress();

        $opts = array('http'=>array('header'=>"User-Agent: StevesCleverAddressScript 3.7.6\r\n"));
        $context = stream_context_create($opts);
        $url = 'https://nominatim.openstreetmap.org/search.php?q=' . rawurlencode($city) . '%20' . rawurlencode($address) . '&format=json';
        $file = file_get_contents($url, false, $context);
        $json = json_decode($file, true);
        $lat = $json[0]['lat'];
        $lon = $json[0]['lon'];
        $token = '4TozhmTJ9jLsEVJRLrWHXF50V0xqSvy8OgXCfVJ6p0mZrEY6Ts6iU5Sear5w3gHq';
        $urlElevation = 'https://api.jawg.io/elevations?locations=' . $lat . ',' . $lon . '&access-token=' . $token;
        $fileElevation = file_get_contents($urlElevation, false, $context);
        $jsonElevation = json_decode($fileElevation, true);
        $elevation = $jsonElevation[0]['elevation'];
        $object->setLatitude($lat);
        $object->setLongitude($lon);
        $object->setAltitude($elevation);
    }

}